### ISSUE TITLE
2-day

### ISSUE THREAD

**Issue by manoharv2512** [manoharv2512/Code_Compass_019#1]
- [x] Login page
- [x] Logout Page

make the pages
- [x] Location page
- [x] Hotel Page
- [x] Cabs page

try to complete half task before tomorrow EOD

**Comment by manojRawat5** [comment]
Signup and Signin page completed working on others pages

**Comment by manojRawat5** [comment]
Necessary Component for Trip plan Completed

**Comment by manoharv2512** [comment]
Thank you Manoj.
