### ISSUE TITLE
Cloning the project

### ISSUE THREAD

**Issue by manoharv2512** [manoharv2512/Code_Compass_019#5]
- [x] Clone the project
- [x] Create Daily Branches - use student code for naming

Project setup...

**Comment by manoharv2512** [comment]
DONE...
-  Clone the project
-  Create Daily Branches - use student code for naming

**Comment by i-am-shank** [comment]
DONE..
- Cloned the project
- Created daily branch.. initialising folder-structure

**Comment by manojRawat5** [comment]
cloning complete
